# Generated by Django 5.2.7 on 2025-11-04 06:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('HMS_app', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='biodata',
            old_name='Name',
            new_name='gender',
        ),
        migrations.AddField(
            model_name='biodata',
            name='name',
            field=models.CharField(default=0, max_length=50),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='biodata',
            name='age',
            field=models.IntegerField(),
        ),
        migrations.CreateModel(
            name='Item',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('bio', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='HMS_app.biodata')),
            ],
        ),
        migrations.CreateModel(
            name='Cart',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('qty', models.CharField(max_length=10)),
                ('price', models.CharField(max_length=20)),
                ('bio', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='HMS_app.biodata')),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='HMS_app.item')),
            ],
        ),
    ]
