# Generated by Django 5.2.7 on 2025-11-04 07:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('HMS_app', '0002_rename_name_biodata_gender_biodata_name_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Nysc_bio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('age', models.IntegerField()),
                ('gender', models.CharField(max_length=10)),
                ('state', models.CharField(max_length=50)),
                ('batch', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Nysc_bank_account',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('account_number', models.CharField(max_length=20)),
                ('bank_name', models.CharField(max_length=50)),
                ('account_type', models.CharField(max_length=20)),
                ('date_created', models.DateTimeField(auto_now_add=True)),
                ('nysc_bio', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='HMS_app.nysc_bio')),
            ],
        ),
        migrations.CreateModel(
            name='Educational_qualification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('institution_name', models.CharField(max_length=100)),
                ('degree_obtained', models.CharField(max_length=100)),
                ('graduation_year', models.IntegerField()),
                ('grade', models.CharField(max_length=10)),
                ('nysc_bio', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='HMS_app.nysc_bio')),
            ],
        ),
        migrations.CreateModel(
            name='Batch_details',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('batch_name', models.CharField(max_length=50)),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
                ('nysc_bio', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='HMS_app.nysc_bio')),
            ],
        ),
        migrations.CreateModel(
            name='Nysc_project',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('project_title', models.CharField(max_length=100)),
                ('project_description', models.TextField()),
                ('supervisor_name', models.CharField(max_length=50)),
                ('location', models.CharField(max_length=100)),
                ('nysc_bio', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='HMS_app.nysc_bio')),
            ],
        ),
        migrations.CreateModel(
            name='Social_handles',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('twitter_handle', models.CharField(max_length=50)),
                ('facebook_handle', models.CharField(max_length=50)),
                ('instagram_handle', models.CharField(max_length=50)),
                ('nysc_bio', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='HMS_app.nysc_bio')),
            ],
        ),
    ]
