# Generated by Django 5.2.7 on 2025-12-18 12:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('HMS_app', '0003_nysc_bio_nysc_bank_account_educational_qualification_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='RoomStatus',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(max_length=50)),
            ],
        ),
    ]
